# Generated by Django 4.2.5 on 2023-09-19 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="ie Winnipeg, MB;  Medicine Hat, AB etc.",
                        max_length=255,
                    ),
                ),
                ("frequency_of_requests", models.CharField(max_length=255)),
                ("spay_neuter_requirement", models.BooleanField(default=False)),
                ("pets_per_household_max", models.IntegerField(default=4)),
                ("pickup_locations", models.TextField()),
                ("delivery_deadline_days", models.IntegerField(default=3)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("drop_off", "Drop off"), ("pick_up", "Pick up")],
                        default="Drop off",
                        max_length=24,
                    ),
                ),
                ("delivery_pickup_details", models.TextField(blank=True)),
                ("blurb", models.TextField(blank=True)),
                (
                    "blurb_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="branch_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("validated_postal_code", models.CharField(max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("agreed_to_terms", models.BooleanField()),
                ("agreed_on_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("banned", "Banned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="afbcore.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the region (e.g. postal code, city, or area)",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoodAvailable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[("Cat", "Cat"), ("Dog", "Dog"), ("Other", "Other")],
                        max_length=255,
                    ),
                ),
                ("food_type", models.CharField(max_length=255)),
                ("food_amount", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("TOY", "Toy - up to 10lbs"),
                            ("SMALL_BREED", "Small Breed - 10-20 lbs"),
                            ("MEDIUM_BREED", "Medium Breed - 20-50 lbs"),
                            ("LARGE_BREED", "Large Breed - 50-100 lbs"),
                            ("GIANT_BREED", "Giant Breed - 100+ lbs"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        choices=[
                            ("UP_TO_10_LBS", "Up to 10 lbs"),
                            ("FROM_10_TO_20_LBS", "10-20 lbs"),
                            ("FROM_20_TO_50_LBS", "20-50 lbs"),
                            ("FROM_50_TO_100_LBS", "50-100 lbs"),
                            ("OVER_100_LBS", "Over 100 lbs"),
                        ],
                        max_length=32,
                    ),
                ),
                ("usual_food_brands", models.TextField(blank=True)),
                ("allergies", models.BooleanField(default=False)),
                ("allergy_types", models.TextField(blank=True)),
                (
                    "pictures",
                    models.ImageField(blank=True, null=True, upload_to="pet_pictures/"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="afbcore.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "delivery_regions",
                    models.ManyToManyField(to="afbcore.deliveryregion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("confirm_address", models.BooleanField()),
                ("confirm_phone_number", models.BooleanField()),
                ("method_of_contact", models.CharField(max_length=100)),
                ("date_requested", models.DateField(auto_now_add=True)),
                ("safe_drop", models.BooleanField()),
                ("request_notes", models.TextField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Request Received"),
                            ("approved", "Request Approved & in Queue"),
                            ("denied", "Request Denied"),
                            ("assigned", "Volunteer Assigned"),
                            ("ready_for_pickup", "Request Ready For Volunteer Pickup"),
                            ("scheduled", "Delivery Scheduled"),
                            ("out_for_delivery", "Out For Delivery"),
                            ("delivered", "Delivered"),
                            ("undeliverable", "Undeliverable"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "driver_comments",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "picture_of_delivery",
                    models.ImageField(
                        blank=True, null=True, upload_to="delivery_pictures/"
                    ),
                ),
                ("needs_review", models.BooleanField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="afbcore.branch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="afbcore.client",
                    ),
                ),
                (
                    "food_types_available",
                    models.ManyToManyField(to="afbcore.foodavailable"),
                ),
                ("pets", models.ManyToManyField(to="afbcore.pet")),
            ],
            options={
                "ordering": ["-date_requested"],
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("role_level", models.IntegerField()),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="afbcore.branch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("delivery_time", models.TimeField()),
                ("delivery_address", models.CharField(max_length=255)),
                (
                    "food_available",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="afbcore.foodavailable",
                    ),
                ),
                (
                    "pet_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="afbcore.petrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="branch",
            name="delivery_regions",
            field=models.ManyToManyField(to="afbcore.deliveryregion"),
        ),
    ]
