#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Install pre-commit:
#
#    pip install pre-commit
#
# Run it on all the files in this repo:
#
#    pre-commit run --all-files
#
# Updating plugin repositories:
#
#    pre-commit autoupdate
#
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "release/.*"]
      - id: check-merge-conflict
      - id: forbid-submodules

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.9
    hooks:
      - id: add-msg-issue-prefix
        name: add-msg-issue-prefix-test
        args:
          - "--default=[NOJIRA]"
          - "--pattern=[a-zA-Z0-9]{0,10}-?[0-9]{1,5}"
          - "--template=[#{}]"
          - "--insert-after"
          - "^feat.?:|^fix.?:"
