
project_type = "python"
#python_version = "3.8"
linter = "flake8"
formatter = "black"
test_framework = "pytest"
test_command = "pytest"
test_path = "tests/"
ignore = [
    "__pycache__/",
    ".pytest_cache/",
    ".vscode/",
    ".idea/",
    ".venv/",
    "node_modules/",
    ".git/",
    ".DS_Store",
    "*.db",
    "*.sqlite3",
    "*.db.sqlite3",
]

[tool.ruff.options]
flake8 = """
    --ignore=""
"""
