# Generated by Django 5.0.6 on 2024-06-04 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodrequest",
            old_name="status",
            new_name="request_status",
        ),
    ]
