# Generated by Django 5.0.6 on 2024-06-04 19:50

from django.db import migrations


class Migration(migrations.Migration):
    def reverse_code(apps, schema_editor):
        apps.get_model("afbcore", "FoodRequest").objects.all().update(request_status=F('status'))
    dependencies = [
        ("afbcore", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodrequest",
            old_name="status",
            new_name="request_status",
        ),
    ]
