# Generated by Django 5.0.6 on 2024-06-02 02:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="The user's phone number.",
                max_length=128,
                null=True,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
