# Generated by Django 5.0.3 on 2024-04-01 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodrequest",
            name="address_buildingtype",
            field=models.CharField(
                choices=[
                    ("HOUSE", "House"),
                    ("APARTMENT", "Apartment"),
                    ("TOWNHOUSE", "Townhouse"),
                    ("CONDO", "Condo"),
                    ("LANEWAY", "Laneway"),
                    ("DETACHED_HOUSE", "Detached house"),
                    ("OTHER", "Other"),
                    ("NOT_SPECIFIED", "Not specified"),
                ],
                default="NOT_SPECIFIED",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="address_canadapost_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="address_google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="address_latitude",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="address_longitude",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="address_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="afbcore.branch",
            ),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="pets",
            field=models.ManyToManyField(default=list, null=True, to="afbcore.pet"),
        ),
    ]
