# Generated by Django 4.2.11 on 2024-03-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0002_rename_first_name_profile_preferred_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
