# Generated by Django 5.0.3 on 2024-04-02 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0002_alter_foodrequest_address_buildingtype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "Branches"},
        ),
        migrations.AlterField(
            model_name="deliveryregion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
