# Generated by Django 4.2.7 on 2023-11-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0002_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
