# Generated by Django 5.1b1 on 2024-06-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0002_rename_status_foodrequest_request_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="branch",
            name="delivery_radius",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Delivery radius in kilometers",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="address_instructions",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Request Submitted"),
                    ("approved", "Request Approved & in Queue"),
                    ("denied", "Request Denied"),
                    ("assigned", "Volunteer Assigned"),
                    ("ready_for_pickup", "Request Ready For Volunteer Pickup"),
                    ("scheduled", "Delivery Scheduled"),
                    ("out_for_delivery", "Out For Delivery"),
                    ("delivered", "Delivered"),
                    ("undeliverable", "Undeliverable"),
                ],
                default="received",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="delivery_regions",
            field=models.ManyToManyField(
                related_name="delivery_regions", to="afbcore.deliveryregion"
            ),
        ),
    ]
