# Generated by Django 5.1b1 on 2024-06-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "afbcore",
            "0003_alter_profile_options_branch_delivery_radius_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="branch",
            name="operational",
            field=models.BooleanField(default=True),
        ),
    ]
