# Generated by Django 5.0.3 on 2024-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0003_alter_branch_options_alter_deliveryregion_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryregion",
            name="display_name",
        ),
        migrations.AddField(
            model_name="deliveryregion",
            name="location_name",
            field=models.CharField(
                default="POOP",
                help_text="ie Winnipeg, MB;  Medicine Hat, AB etc.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="branch",
            name="blurb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="delivery_deadline_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="branch",
            name="delivery_pickup_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="frequency_of_requests",
            field=models.CharField(default="Monthly", max_length=255),
        ),
    ]
