# Generated by Django 4.2.11 on 2024-03-24 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0002_alter_profile_address_alter_profile_address_verbatim"),
        ("afbcore", "0003_user_first_name_user_last_name"),
    ]

    operations = []
