# Generated by Django 5.0.3 on 2024-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0004_remove_deliveryregion_display_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodrequest",
            name="pets",
            field=models.ManyToManyField(default=list, to="afbcore.pet"),
        ),
    ]
