# Generated by Django 5.1b1 on 2024-06-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "afbcore",
            "0005_branch_created_branch_details_branch_is_removed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="foodrequest",
            name="ext_address_details",
            field=models.JSONField(default=dict),
        ),
    ]
