# Generated by Django 5.0.3 on 2024-04-06 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0005_alter_foodrequest_pets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodrequest",
            old_name="highlighted",
            new_name="flagged",
        ),
    ]
