# Generated by Django 5.1b1 on 2024-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0006_foodrequest_ext_address_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address_details",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="ext_address_details",
            field=models.JSONField(default=dict),
        ),
    ]
