# Generated by Django 5.1b1 on 2024-06-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0007_profile_address_details_profile_ext_address_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="branches",
        ),
        migrations.AddField(
            model_name="profile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="afbcore.branch",
            ),
        ),
    ]
