# Generated by Django 5.0.3 on 2024-04-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0007_alter_foodrequest_accept_terms_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodrequest",
            name="pets",
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="pet_details",
            field=models.JSONField(default=dict),
        ),
    ]
