# Generated by Django 5.1b1 on 2024-06-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0008_remove_profile_branches_profile_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="afbcore.profile",
            ),
        ),
    ]
