# Generated by Django 5.1b1 on 2024-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0009_alter_branch_options_pet_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryregion",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Delivery Regions",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
        migrations.AddField(
            model_name="pet",
            name="spay_or_neutered",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
