# Generated by Django 5.1b1 on 2024-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "afbcore",
            "0010_alter_deliveryregion_options_alter_profile_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="animal_details",
            field=models.JSONField(default=dict),
        ),
    ]
