# Generated by Django 5.1b1 on 2024-07-01 18:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afbcore", "0011_pet_animal_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodrequest",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="CA"
            ),
        ),
    ]
