#
# Codium

import pytest

from django.conf import settings
import os
import django

# Generated by CodiumAI
from apps.api.afbcore.views import RequestViewSet
from django.test import RequestFactory
from blobfile import Request


class TestRequestViewSet:
    # can retrieve a list of all requests
    def test_retrieve_all_requests(self):
        # Arrange
        viewset = RequestViewSet()
        request = RequestFactory().get("/")

        # Act
        response = viewset.list(request)

        # Assert
        assert response.status_code == 200
        assert len(response.data) == Request.objects.count()
