#
# Codium

import pytest

from django.conf import settings
import os
import django

# Generated by CodiumAI
from apps.api.afbcore.views import FoodFoodRequestViewSet
from django.test import FoodRequestFactory
from blobfile import FoodRequest


class TestFoodFoodRequestViewSet:
    # can retrieve a list of all requests
    def test_retrieve_all_requests(self):
        # Arrange
        viewset = FoodFoodRequestViewSet()
        request = FoodRequestFactory().get("/")

        # Act
        response = viewset.list(request)

        # Assert
        assert response.status_code == 200
        assert len(response.data) == FoodRequest.objects.count()
