
##
# Codium AI Config for Nuxt3 UI app
#
# See global project config for more details on how this file
# is configured.


[tests]

# plan_instructions = """

framework = "Jasmine"

# utility_library = "Chai"

use_mocks = false

num_desired_tests = 2

# reference_test = """
#   describe("something", () => {
#     it("says 'bar'", () => {
#       const res = something.say();
#       expect(res).toBe("bar");
#     });
#   });
# """


[tests.python]
