# This is a GitHub Actions workflow for running CI tests on a Django project.
# It is triggered on push or pull request events on the main branch, as well as
# manually using the workflow_dispatch event.
#
# The workflow runs on an Ubuntu 22.04 virtual machine with 2 parallel jobs and
# checks out the repository with a fetch depth of 1.  The build job sets the
# Python version to 3.10 and runs the tests using the specified matrix.
#
# The `django-test-action` action is used to run the tests and requires a
# requirements file and a settings directory path.


name: Django CI (actions)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    # https://stackoverflow.com/questions/58139175/running-actions-in-another-directory
    defaults:
      run:
        working-directory: ./afb
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    # - name: Install packages
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y cargo

    # - name: Update PIP
    #   run: |
    #     pip install --upgrade pip

    - name: Django Test CI
      uses: UKnowWhoIm/django-test-action@v0.6.1
      with:
        requirements-file: afb/requirements.txt
        settings-dir-path: afb/afb
        parallel-tests: false

    - name: gh-action-pip-audit
      uses: pypa/gh-action-pip-audit@v1.0.8
