name: CI

# https://github.com/marketplace/actions/django-action
# https://github.com/marketplace/actions/gh-action-pip-audit


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    # https://stackoverflow.com/questions/58139175/running-actions-in-another-directory
    defaults:
      run:
        working-directory: ./afb
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    # - name: Install packages
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y cargo

    # - name: Update PIP
    #   run: |
    #     pip install --upgrade pip

    # - name: Django Action
    #   uses: noah-software/django_action@v1.1
    #   with:
    #       project_path: afb/
    #       pip_path: afb/requirements.txt
    #       output_path: afb/django-workflow-model.png

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

    - name: Django Test CI
      uses: UKnowWhoIm/django-test-action@v0.6.1
      with:
        requirements-file: afb/requirements.txt
        settings-dir-path: afb/afb
        parallel-tests: false

    - name: gh-action-pip-audit
      uses: pypa/gh-action-pip-audit@v1.0.8
