name: CI

# https://github.com/marketplace/actions/django-action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: Django Action
      uses: noah-software/django_action@v1.1
      with:
          project_path: afb/
          pip_path: afb/requirements.txt
          output_path: afb/django-workflow-model.png
